### ISSUE TITLE
Reshape fails for training ontonotes

### ISSUE THREAD

**Issue by vasilikivmo** [ghaddarAbs/NER-with-LS#3]
Hello, while trying to run the model for _ontonotes_, with tensorflow 1.6 I get the error:

`InvalidArgumentError (see above for traceback): Reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
         [[Node: ontonotes/Reshape_1 = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ontonotes/max_pooling1d/Squeeze, ontonotes/Reshape_1/shape)]]`

Do you maybe know where the error comes from? I am using the exact dataset path as suggested by you

Thank you in advance for your feedback.
Vasiliki

**Comment by ghaddarAbs** [comment]
Mmmm ... this is weird the model has been tested without problems by many users...
I think that the bug comes from 
https://github.com/ghaddarAbs/NER-with-LS/blob/3e6e8c976c6a9303e82e4a0de51cc97b5a18d571/model.py#L133

Does the bug happen during graph construction (most probably) or during training?

I think that the bug happens because it can't infer the length of the sequence `ntime_steps`
If this is true I think that it's a TensorFlow version issue ... a had some problems with CNN using different versions of TensorFlow.

Ok I will try to replicate the bug on my machine while trying **lower** TensorFlow versions

**Comment by vasilikivmo** [comment]
After trying to debug it I see that it fails in line 273 of model.py, inside the for loop, and during training. I am currently using the minimum version of tensorflow that you suggest in the repo description (1.6). 

The weird part is that with the conll parameter the model runs fine. Is there any chance that I am missing something in the input dataset configuration?
Additionally, when I was using the latest version of tensorflow (1.14) I was receiving another similar error about the input again. So, indeed I do believe it's because of the tensorflow version, but do you think it's proper to use a lower than 1.6 version?

Thank you for your quick reply.

Best,
Vasiliki

**Comment by ghaddarAbs** [comment]
I tested the model on ontonotes ... it works well with tf 1.6 and tf 1.14 ....
there is a small modification to do while preprocessing ontonotes:
change `/path/to/conll-2012/v4/data/development ` to `/path/to/conll-2012/v4/data/dev`
and check the ontonotes.dev.iob in your `/data`
